export const mockActivityStatsData = [
  {
    type: "Buy",
    crypto_currency: "BTC",
    count: 99,
    amount: "1.39037954",
    fiat_currency: "USD",
    amount_fiat: "17654.00",
  },
  {
    type: "Buy",
    crypto_currency: "LTC",
    count: 1,
    amount: "1.00011886",
    fiat_currency: "USD",
    amount_fiat: "31.44",
  },
  {
    type: "Buy",
    crypto_currency: "ZRX",
    count: 2,
    amount: "370.14728708",
    fiat_currency: "USD",
    amount_fiat: "200.00",
  },
  {
    type: "Buy",
    crypto_currency: "ADA",
    count: 1,
    amount: "292.836891",
    fiat_currency: "USD",
    amount_fiat: "500.00",
  },
  {
    type: "Buy",
    crypto_currency: "ANKR",
    count: 1,
    amount: "2959.84153619 ",
    fiat_currency: "USD",
    amount_fiat: "500",
  },
  {
    type: "Buy",
    crypto_currency: "SHIB",
    count: 4,
    amount: "128486",
    fiat_currency: "USD",
    amount_fiat: "283.73325682",
  },
  {
    type: "Buy",
    crypto_currency: "ETH",
    count: 4,
    amount: "0.20803916",
    fiat_currency: "USD",
    amount_fiat: "444.36",
  },
  {
    type: "Buy",
    crypto_currency: "ROSE",
    count: 1,
    amount: "450.430999459",
    fiat_currency: "USD",
    amount_fiat: "100.00",
  },
  {
    type: "Buy",
    crypto_currency: "MATIC",
    count: 1,
    amount: "4.14593699",
    fiat_currency: "USD",
    amount_fiat: "5.12",
  },
  {
    type: "Buy",
    crypto_currency: "USDC",
    count: 1,
    amount: "105.030000",
    fiat_currency: "USD",
    amount_fiat: "105.03",
  },
  {
    type: "Sell",
    crypto_currency: "SHIB",
    count: 1,
    amount: "128486",
    fiat_currency: "USD",
    amount_fiat: "283.73325688",
  },
  {
    type: "Sell",
    crypto_currency: "CBETH",
    count: 1,
    amount: "0.74639167",
    fiat_currency: "USD",
    amount_fiat: "1146.72",
  },
  {
    type: "Sell",
    crypto_currency: "BCH",
    count: 1,
    amount: "0.03852072",
    fiat_currency: "USD",
    amount_fiat: "51.29",
  },
  {
    type: "Sell",
    crypto_currency: "LTC",
    count: 3,
    amount: "0.39950649",
    fiat_currency: "USD",
    amount_fiat: "95.34",
  },
  {
    type: "Sell",
    crypto_currency: "ZRX",
    count: 1,
    amount: "313.80519208",
    fiat_currency: "USD",
    amount_fiat: "75.90",
  },
  {
    type: "Send",
    crypto_currency: "ETH",
    count: 7,
    amount: "0.25113140",
    fiat_currency: "USD",
    amount_fiat: "505.16",
  },
  {
    type: "Send",
    crypto_currency: "LTC",
    count: 1,
    amount: "0.60061237",
    fiat_currency: "USD",
    amount_fiat: "209.12",
  },
  {
    type: "Send",
    crypto_currency: "USDC",
    count: 1,
    amount: "105.030000",
    fiat_currency: "USD",
    amount_fiat: "105.03",
  },
  {
    type: "Send",
    crypto_currency: "ADA",
    count: 1,
    amount: "299.680349",
    fiat_currency: "USD",
    amount_fiat: "108.09",
  },
  {
    type: "Send",
    crypto_currency: "ANKR",
    count: 1,
    amount: "2072",
    fiat_currency: "USD",
    amount_fiat: "7133262",
  },
  {
    type: "Send",
    crypto_currency: "MATIC",
    count: 1,
    amount: "4.14593699",
    fiat_currency: "USD",
    amount_fiat: "5.09",
  },
  {
    type: "Send",
    crypto_currency: "ETH2",
    count: 1,
    amount: "0.75512731",
    fiat_currency: "USD",
    amount_fiat: "997.02",
  },
  {
    type: "Recieve",
    crypto_currency: "ZRX",
    count: 3,
    amount: "8.82352944",
    fiat_currency: "USD",
    amount_fiat: "2.94",
  },
  {
    type: "Recieve",
    crypto_currency: "ADA",
    count: 131,
    amount: "311.970701",
    fiat_currency: "USD",
    amount_fiat: "112.69",
  },
  {
    type: "Recieve",
    crypto_currency: "CBETH",
    count: 1,
    amount: "0.74639167",
    fiat_currency: "USD",
    amount_fiat: "956.45",
  },
  {
    type: "Withdrawal",
    crypto_currency: "USD",
    count: 4,
    fiat_currency: "USD",
    amount: "",
    amount_fiat: "240.61",
  },
];
